---
name: Test JSON files
on:
  push:
    paths:
      - .github/workflows/jsontest.yaml
      - '**.json'
      - tests/checkjson.py
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check JSON files
        run: |
          ./tests/checkjson.py
